export const data = {
  result: {
    branch: [
      {
        branchcode: "002",
        branchtype: [
          {
            id: 801,
            branchcode: "002",
            approveD_BY: "Juliet Ohankwere",
            denomination: "1000",
            files: "string",
            status: "1",
            currencynumber: "12345",
            branchname: "Delta",
            initiatoR_BY: "Adeshina",
            initiatoR_DATE: "14/Sep/2023",
            approvE_DATE: "15-Sep-2023 10:41:26",
          },
          {
            id: 802,
            branchcode: "002",
            approveD_BY: "Janice Jennet",
            denomination: "200",
            files: "string",
            status: "1",
            currencynumber: "123",
            branchname: "Delta",
            initiatoR_BY: "Adeshina",
            initiatoR_DATE: "14/Sep/2023",
            approvE_DATE: "15-Sep-2023 10:41:26",
          },
        ],
      },
      {
        branchcode: "001",
        branchtype: [
          {
            id: 803,
            branchcode: "001",
            approveD_BY: "Juliet Ohankwere",
            denomination: "2000",
            files: "string",
            status: "1",
            currencynumber: "123456",
            branchname: "ADEOLA HOPEWELL",
            initiatoR_BY: "Niyi",
            initiatoR_DATE: "03/Sep/2023",
            approvE_DATE: "15-Sep-2023 10:41:22",
          },
          {
            id: 804,
            branchcode: "001",
            approveD_BY: "Juliet Ohankwere",
            denomination: "100",
            files: "string",
            status: "1",
            currencynumber: "6543",
            branchname: "ADEOLA HOPEWELL",
            initiatoR_BY: "Adeshina",
            initiatoR_DATE: "14/Sep/2023",
            approvE_DATE: "15-Sep-2023 10:41:26",
          },
        ],
      },
      {
        branchcode: "003",
        branchtype: [
          {
            id: 849,
            branchcode: "003",
            approveD_BY: "Mike",
            denomination: "10000",
            files: "string",
            status: "1",
            currencynumber: "7654565",
            branchname: "Warri",
            initiatoR_BY: "Yemi",
            initiatoR_DATE: "14/Sep/2023",
            approvE_DATE: "15-Sep-2023 10:41:26",
          },
          {
            id: 849,
            branchcode: "003",
            approveD_BY: "Mike",
            denomination: "100",
            files: "string",
            status: "1",
            currencynumber: "6776543",
            branchname: "Warri",
            initiatoR_BY: "Yemi",
            initiatoR_DATE: "14/Sep/2023",
            approvE_DATE: "15-Sep-2023 10:41:26",
          },
        ],
      },
    ],
  },
};
